apiVersion: apps/v1
kind: Deployment
metadata:
  name: eztopo-web
spec:
  selector:
    matchLabels:
      app: eztopo-web
  replicas: 1
  template:
    metadata:
      labels:
        app: eztopo-web
    spec:
      containers:
        - name: master
          image: bryanturns/eztopo-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
