apiVersion: v1
kind: Service
metadata:
  name: eztopo-web
  labels:
    app: eztopo-web
spec:
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
  selector:
    app: eztopo-web
