apiVersion: v1
kind: Service
metadata:
  name: eztopo-web
  labels:
    app: eztopo-web
spec:
  clusterIP: "10.96.75.120"
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
  selector:
    app: eztopo-web
