apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  clusterIP: 10.97.72.90
  ports:
    - protocol: "TCP"
      port: 9000
      targetPort: 9000
  selector:
    app: minio
