apiVersion: v1
kind: Service
metadata:
  name: eztopo-output
  labels:
    app: eztopo-output
spec:
  ports:
    - protocol: "TCP"
      port: 50051
      targetPort: 50051
  selector:
    app: eztopo-output
