apiVersion: v1
kind: Service
metadata:
  name: eztopo-predictor
  labels:
    app: eztopo-predictor
spec:
  clusterIP: 10.98.162.175
  ports:
    - protocol: "TCP"
      port: 50051
      targetPort: 50051
  selector:
    app: eztopo-predictor
