apiVersion: apps/v1
kind: Deployment
metadata:
  name: eztopo-predictor
spec:
  selector:
    matchLabels:
      app: eztopo-predictor
  replicas: 1
  template:
    metadata:
      labels:
        app: eztopo-predictor
    spec:
      containers:
        - name: master
          image: bryanturns/eztopo-predictor:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secret-volume
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: service-key
