apiVersion: v1
kind: Service
metadata:
  name: eztopo-chopper
  labels:
    app: redis
spec:
  ports:
    - protocol: "TCP"
      port: 50051
      targetPort: 50051
  selector:
    app: eztopo-chopper
