apiVersion: apps/v1
kind: Deployment
metadata:
  name: eztopo-rest
spec:
  selector:
    matchLabels:
      app: eztopo-rest
  replicas: 1
  template:
    metadata:
      labels:
        app: eztopo-rest
    spec:
      containers:
        - name: master
          image: bryanturns/eztopo-rest:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
          ports:
            - containerPort: 5000
