apiVersion: v1
kind: Service
metadata:
  name: eztopo-rest
  labels:
    app: redis
spec:
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  selector:
    app: eztopo-rest
